routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\IndexController;
use App\Http\Controllers\InstallationController;
use Mcamara\LaravelLocalization\Facades\LaravelLocalization;
use App\Http\Controllers\MailController;
use App\Http\Controllers\PageController;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\magicaiUpdaterController;
use App\Http\Controllers\TestController;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\Config;
use RachidLaasri\LaravelInstaller\Middleware\ApplicationStatus;
use App\Http\Controllers\Common\SitemapController;

Route::get('/test', [TestController::class, 'test']);

Route::group(['prefix' => LaravelLocalization::setLocale(), 'middleware' => [ 'checkInstallation', 'localeSessionRedirect', 'localizationRedirect', 'localeViewPath' ]], function() {
    Route::get('/', [IndexController::class, 'index'])->name('index');
    
    Route::get('/privacy-policy', [PageController::class, 'pagePrivacy']);
    Route::get('/terms', [PageController::class, 'pageTerms']);


	Route::get('/page/{slug}', [PageController::class, 'pageContent']);
	Route::get('/blog', [BlogController::class, 'index']);
	Route::get('/blog/{slug}', [BlogController::class, 'post']);
	Route::get('/blog/tag/{slug}', [BlogController::class, 'tags']);
	Route::get('/blog/category/{slug}', [BlogController::class, 'categories']);
	Route::get('/blog/author/{slug}', [BlogController::class, 'author']);
});
Route::get('/sitemap.xml', [SitemapController::class, "index"]);

Route::get('/activate', [IndexController::class, 'activate']);

Route::get('/confirm/email/{email_confirmation_code}', [MailController::class, 'emailConfirmationMail']);
// Route::get('/confirm/email/{password_reset_code}', [MailController::class, 'emailPasswordResetEmail']);


//Route::get('/install-script-env-editor', [InstallationController::class, 'envFileEditor'])->name('installer.envEditor');
//Route::post('/install-script-env-editor/save', [InstallationController::class, 'envFileEditorSave'])->name('installer.envEditor.save');
//Route::get('/install-script', [InstallationController::class, 'install'])->name('installer.install');
Route::get('/upgrade-script', [InstallationController::class, 'upgrade'])->withoutMiddleware(
    ApplicationStatus::class
);

Route::get('/update-manual', [InstallationController::class, 'updateManual'])->withoutMiddleware(
    ApplicationStatus::class
);

Route::post('/install-extension/{slug}', [InstallationController::class, 'installExtension']);
Route::post('/uninstall-extension/{slug}', [InstallationController::class, 'uninstallExtension']);


// Clear log file
Route::get('/clear-log', function () {
    $logFile = storage_path('logs/laravel.log');

    if (file_exists($logFile)) {
        unlink($logFile);
    }

    return response()->json(['success' => true]);
});

Route::get('/debug/{token}', function ($token) {
    $storedHash = Config::get('app.debug_hash');
    $hashedToken = Hash::make($token);
    if (Hash::check($token, $storedHash)) {
		$currentDebugValue = env('APP_DEBUG', false);
		$newDebugValue = !$currentDebugValue;
		$envContent = file_get_contents(base_path('.env'));
		$envContent = preg_replace('/^APP_DEBUG=.*/m', "APP_DEBUG=" . ($newDebugValue ? 'true' : 'false'), $envContent);
		file_put_contents(base_path('.env'), $envContent);
		Artisan::call('config:clear');
		return redirect()->back()->with('message', 'Debug mode updated successfully.');
    } else {
        return "Invalid token!";
    }
});
// cache clear
Route::get('/cache-clear', function () {
    try {
        Artisan::call('optimize:clear');
        return response()->json(['success' => true]);
    } catch (\Throwable $th) {
        return response()->json(['success' => false]);
    }
})->name('cache.clear');


Route::get('/check-subscription-end', function () {
    Artisan::call('schedule:run');
    return 'Schedule initiated.';
});
//Updater

Route::get('magicai.updater.check',[magicaiUpdaterController::class, 'check']);
Route::get('magicai.updater.currentVersion', [magicaiUpdaterController::class, 'getCurrentVersion']);
Route::get('magicai.updater.update', [magicaiUpdaterController::class, 'update'])
    ->withoutMiddleware(ApplicationStatus::class)
    ->middleware('admin');


if (file_exists(base_path('routes/custom_routes_web.php'))) {
    include base_path('routes/custom_routes_web.php');
}

require __DIR__.'/auth.php';
require __DIR__.'/panel.php';
require __DIR__.'/webhooks.php';

app/Models/Usage.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;
use Carbon\Carbon;

class Usage extends Model
{
	protected $table = 'usage';
	protected $fillable = [
		'total_user_count',
		'this_week_user_count',
		'last_week_user_count',
		'total_word_count',
        'this_week_word_count',
        'last_week_word_count',
        'total_image_count',
        'this_week_image_count',
        'last_week_image_count'
	];

	public static function getSingle()
    {
        return static::firstOrCreate([]);
    }

    // Define method to update word count
    public function updateWordCounts($count)
    {
        $this->total_word_count += $count;
        $this->this_week_word_count += $count;

        // Check if a week has passed since the last update
        if ($this->updated_at && Carbon::now()->diffInWeeks($this->updated_at) >= 1) {
            // Move this week counts to last week counts
            $this->last_week_word_count = $this->this_week_word_count;
            $this->this_week_word_count = 0;
        }

        $this->save();
    }

    // Define method to update image count
    public function updateImageCounts($count)
    {
        $this->total_image_count += $count;
        $this->this_week_image_count += $count;

        // Check if a week has passed since the last update
        if ($this->updated_at && Carbon::now()->diffInWeeks($this->updated_at) >= 1) {
            // Move this week counts to last week counts
            $this->last_week_image_count = $this->this_week_image_count;
            $this->this_week_image_count = 0;
        }

        $this->save();
    }

	// Define method to update user count
	public function updateUserCount($count)
	{
		$this->total_user_count += $count;
		$this->this_week_user_count += $count;

		// Check if a week has passed since the last update
		if ($this->updated_at && Carbon::now()->diffInWeeks($this->updated_at) >= 1) {
			// Move this week counts to last week counts
			$this->last_week_user_count = $this->this_week_user_count;
			$this->this_week_user_count = 0;
		}

		$this->save();
	}

	// Define method to update sales count
	public function updateSalesCount($count)
	{
		$this->total_sales += $count;
		$this->this_week_sales += $count;

		// Check if a week has passed since the last update
		if ($this->updated_at && Carbon::now()->diffInWeeks($this->updated_at) >= 1) {
			// Move this week counts to last week counts
			$this->last_week_sales = $this->this_week_sales;
			$this->this_week_sales = 0;
		}

		$this->save();
	}

    // Override update method to update counts
    public function update(array $attributes = [], array $options = [])
    {
        parent::update($attributes, $options);
        // Update counts
        $this->updateCounts();
    }

    // Method to update counts after create or update
    protected function updateCounts()
    {
        // Get the current week number
        $currentWeek = Carbon::now()->weekOfYear;

        // Check if the last update week is different from the current week
        if (!$this->updated_at || $this->updated_at->weekOfYear != $currentWeek) {
            // Move this week counts to last week counts
            $this->last_week_word_count = $this->this_week_word_count;
            $this->last_week_image_count = $this->this_week_image_count;
			$this->last_week_user_count = $this->this_week_user_count;
			$this->last_week_sales = $this->this_week_sales;

			// Reset this week counts
            $this->this_week_word_count = 0;
            $this->this_week_image_count = 0;
			$this->this_week_user_count = 0;
			$this->this_week_sales = 0;
        }

        // Update the total counts
        $this->total_word_count = $this->last_week_word_count + $this->this_week_word_count;
        $this->total_image_count = $this->last_week_image_count + $this->this_week_image_count;
		$this->total_user_count = $this->last_week_user_count + $this->this_week_user_count;
		$this->total_sales = $this->last_week_sales + $this->this_week_sales;

        $this->save();
    }
}

app/View/Components/AccordionItem.php
<?php

namespace App\View\Components;

use Closure;
use Illuminate\Contracts\View\View;
use Illuminate\View\Component;

class AccordionItem extends Component
{
    /**
     * Create a new component instance.
     */
    public function __construct(
		public string $id = 'accordion-item-1',
        public string $style = '1',
		public string $title = 'How does it <span class="font-medium">generate responses?</span>',
		public string $content = '<p class="text-lg">Our support team will get assistance from AI-powered suggestions, making it quicker than ever to handle support requests.</p>',
	)
    {
        //
    }

    /**
     * Get the view / contents that represent the component.
     */
    public function render(): View|Closure|string
    {
        return view('components.accordion-item');
    }
}

app/View/Components/Alert.php
<?php

namespace App\View\Components;

use Closure;
use Illuminate\Contracts\View\View;
use Illuminate\View\Component;

class Alert extends Component
{
    /**
     * Create a new component instance.
     */
    public function __construct(
		public string $variant = 'info',
		public string $size = 'md',
		public string $icon = 'tabler-info-circle-filled',
	)
    {
        //
    }

    /**
     * Get the view / contents that represent the component.
     */
    public function render(): View|Closure|string
    {
        return view('components.alert');
    }
}

app/View/Components/AppLayout.php
<?php

namespace App\View\Components;

use Illuminate\View\Component;
use Illuminate\View\View;

class AppLayout extends Component
{
    /**
     * Get the view / contents that represents the component.
     */
    public function render(): View
    {
        return view('layouts.app');
    }
}

app/View/Components/Avatar.php
<?php

namespace App\View\Components;

use App\Models\User;
use Closure;
use Illuminate\Contracts\View\View;
use Illuminate\View\Component;

class Avatar extends Component
{
    /**
     * Create a new component instance.
     */
    public function __construct(
		public User $user
	)
    {
        //
    }

    /**
     * Get the view / contents that represent the component.
     */
    public function render(): View|Closure|string
    {
        return view('components.avatar');
    }
}

app/View/Components/Badge.php
<?php

namespace App\View\Components;

use Closure;
use Illuminate\Contracts\View\View;
use Illuminate\View\Component;

class Badge extends Component
{
    /**
     * Create a new component instance.
     */
    public function __construct(
		public string $variant = 'default',
	) {}

    /**
     * Get the view / contents that represent the component.
     */
    public function render(): View|Closure|string
    {
        return view('components.badge');
    }
}

app/View/Components/BottomMenu.php
<?php

namespace App\View\Components;

use Closure;
use Illuminate\Contracts\View\View;
use Illuminate\View\Component;

class BottomMenu extends Component
{
    /**
     * Create a new component instance.
     */
    public function __construct()
    {
        //
    }

    /**
     * Get the view / contents that represent the component.
     */
    public function render(): View|Closure|string
    {
        return view('components.bottom-menu');
    }
}

app/View/Components/Box.php
<?php

namespace App\View\Components;

use Closure;
use Illuminate\Contracts\View\View;
use Illuminate\View\Component;

class Box extends Component
{
    /**
     * Create a new component instance.
     */
    public function __construct(
		public string $style = '1',
		public string $title = 'AI Generator',
		public string $desc = 'Generate <strong>text, image, code, chat</strong> and even more with MagicAI.',
		public string $badge = '',
		public string $wrapperClass = '',
	)
    {
        //
    }

    /**
     * Get the view / contents that represent the component.
     */
    public function render(): View|Closure|string
    {
        return view('components.box');
    }
}

app/View/Components/Button.php
<?php

namespace App\View\Components;

use Closure;
use Illuminate\Contracts\View\View;
use Illuminate\View\Component;

class Button extends Component
{
    /**
     * Create a new component instance.
     */
    public function __construct(
		public string $tag = 'a',
		public string $href = '#',
		public string $label = 'Button',
		public string $type = '',
		public string $size = '',
		public string $variant = '',
		public string $hoverVariant = '',
	) {}

    /**
     * Get the view / contents that represent the component.
     */
    public function render(): View|Closure|string
    {
        return view('components.button');
    }
}

app/View/Components/Card.php
<?php

namespace App\View\Components;

use Closure;
use Illuminate\Contracts\View\View;
use Illuminate\View\Component;

class Card extends Component
{
    /**
     * Create a new component instance.
     */
    public function __construct(
		public string $head = '',
		public string $foot = '',
		public string $variant = '',
		public string $size = '',
		public string $roundness = '',
	) {}

    /**
     * Get the view / contents that represent the component.
     */
    public function render(): View|Closure|string
    {
        return view('components.card');
    }
}

app/View/Components/ChangeIndicator.php
<?php

namespace App\View\Components;

use Closure;
use Illuminate\Contracts\View\View;
use Illuminate\View\Component;

class ChangeIndicator extends Component
{
    /**
     * Create a new component instance.
     */
    public function __construct(
		public float $value = 0
	)
    {

    }

    /**
     * Get the view / contents that represent the component.
     */
    public function render(): View|Closure|string
    {
        return view('components.change-indicator');
    }
}

app/View/Components/ColorBox.php
<?php

namespace App\View\Components;

use Closure;
use Illuminate\Contracts\View\View;
use Illuminate\View\Component;

class ColorBox extends Component
{
    /**
     * Create a new component instance.
     */
    public function __construct(
		public string $title = 'Digital Agencies',
		public string $color = 'orange'
	)
    {
        //
    }

    /**
     * Get the view / contents that represent the component.
     */
    public function render(): View|Closure|string
    {
        return view('components.color-box');
    }
}

app/View/Components/Documents/Folder.php
<?php

namespace App\View\Components\Documents;

use App\Models\Folders;
use Closure;
use Illuminate\Contracts\View\View;
use Illuminate\View\Component;

class Folder extends Component
{
    /**
     * Create a new component instance.
     */
    public function __construct(
		public Folders $folder,
		public bool $folderSingleView = false
	){}

    /**
     * Get the view / contents that represent the component.
     */
    public function render(): View|Closure|string
    {
        return view('components.documents.folder');
    }
}

app/View/Components/Documents/Item.php
<?php

namespace App\View\Components\Documents;

use App\Models\UserOpenai;
use Closure;
use Illuminate\Contracts\View\View;
use Illuminate\View\Component;

class Item extends Component
{
    /**
     * Create a new component instance.
     */
    public function __construct(
		public UserOpenai $entry,
		public string $style = 'min'
	) {}

    /**
     * Get the view / contents that represent the component.
     */
    public function render(): View|Closure|string
    {
        return view('components.documents.item');
    }
}

app/View/Components/Dropdown/Dropdown.php
<?php

namespace App\View\Components\Dropdown;

use Closure;
use Illuminate\Contracts\View\View;
use Illuminate\View\Component;

class Dropdown extends Component
{
    /**
     * Create a new component instance.
     */
    public function __construct(
		public string $anchor = 'start',
		public string $offsetY = '',
		public string $triggerType = 'hover',
	){}

    /**
     * Get the view / contents that represent the component.
     */
    public function render(): View|Closure|string
    {
        return view('components.dropdown.dropdown');
    }
}

app/View/Components/Dropdown/Item.php
<?php

namespace App\View\Components\Dropdown;

use Closure;
use Illuminate\Contracts\View\View;
use Illuminate\View\Component;

class Item extends Component
{
    /**
     * Create a new component instance.
     */
    public function __construct()
    {
        //
    }

    /**
     * Get the view / contents that represent the component.
     */
    public function render(): View|Closure|string
    {
        return view('components.dropdown.item');
    }
}

app/View/Components/FavoriteButton.php
<?php

namespace App\View\Components;

use Closure;
use Illuminate\Contracts\View\View;
use Illuminate\View\Component;

class FavoriteButton extends Component
{
    /**
     * Create a new component instance.
     */
    public function __construct(
		public string $id,
		public string $updateUrl = '',
		public bool $isFavorite = false,
	)
    {
        //
    }

    /**
     * Get the view / contents that represent the component.
     */
    public function render(): View|Closure|string
    {
        return view('components.favorite-button');
    }
}

resources/views/panel/layout/components/search_results.blade.php
@if(count($template_search)>0)
<ul class="m-0 p-0 list-none font-medium">
    @foreach($template_search as $item)
    <li class="p-2 px-3 border-solid border-b border-t-0 border-r-0 border-l-0 border-[--tblr-border-color] last:border-b-0 transition-colors hover:bg-slate-50  dark:hover:!bg-[rgba(255,255,255,0.05)]">
        @if($item->type == 'text')
            <a href="{{LaravelLocalization::localizeUrl(route('dashboard.user.openai.generator.workbook', $item->slug))}}" class="d-flex align-items-center text-heading !no-underline">
				<span class="avatar w-[43px] h-[43px] [&_svg]:w-[20px] [&_svg]:h-[20px] relative !me-2" style="background: {{$item->color}}">
					@if ( $item->image !== 'none' )
					{!! html_entity_decode($item->image) !!}
					@endif
					@if($item->active == 1)
						<span class="badge bg-green !w-[9px] !h-[9px]"></span>
					@else
						<span class="badge bg-red !w-[9px] !h-[9px]"></span>
					@endif
				</span>
                {{$item->title}}
				<small class="ml-auto text-muted opacity-75">{{__('Template')}}</small>
            </a>
        @elseif($item->type == 'image')
            <a href="{{LaravelLocalization::localizeUrl(route('dashboard.user.openai.generator', $item->slug))}}" class="d-flex align-items-center text-heading !no-underline">
				<span class="avatar w-[43px] h-[43px] [&_svg]:w-[20px] [&_svg]:h-[20px] relative !me-2" style="background: {{$item->color}}">
					@if ( $item->image !== 'none' )
					{!! html_entity_decode($item->image) !!}
					@endif
					@if($item->active == 1)
						<span class="badge bg-green !w-[9px] !h-[9px]"></span>
					@else
						<span class="badge bg-red !w-[9px] !h-[9px]"></span>
					@endif
				</span>
                {{$item->title}}
				<small class="ml-auto text-muted opacity-75">{{__('Template')}}</small>
            </a>
        @elseif($item->type == 'audio')
            <a href="{{LaravelLocalization::localizeUrl(route('dashboard.user.openai.generator', $item->slug))}}" class="d-flex align-items-center text-heading !no-underline">
				<span class="avatar w-[43px] h-[43px] [&_svg]:w-[20px] [&_svg]:h-[20px] relative !me-2" style="background: {{$item->color}}">
					@if ( $item->image !== 'none' )
					{!! html_entity_decode($item->image) !!}
					@endif
					@if($item->active == 1)
						<span class="badge bg-green !w-[9px] !h-[9px]"></span>
					@else
						<span class="badge bg-red !w-[9px] !h-[9px]"></span>
					@endif
				</span>
                {{$item->title}}
				<small class="ml-auto text-muted opacity-75">{{__('Template')}}</small>
            </a>
        @elseif($item->type == 'code')
            <a href="{{LaravelLocalization::localizeUrl(route('dashboard.user.openai.generator.workbook', $item->slug))}}" class="d-flex align-items-center text-heading !no-underline">
				<span class="avatar w-[43px] h-[43px] [&_svg]:w-[20px] [&_svg]:h-[20px] relative !me-2" style="background: {{$item->color}}">
					@if ( $item->image !== 'none' )
					{!! html_entity_decode($item->image) !!}
					@endif
					@if($item->active == 1)
						<span class="badge bg-green !w-[9px] !h-[9px]"></span>
					@else
						<span class="badge bg-red !w-[9px] !h-[9px]"></span>
					@endif
				</span>
                {{$item->title}}
				<small class="ml-auto text-muted opacity-75">{{__('Template')}}</small>
            </a>
        @endif
    </li>
    @endforeach
</ul>
@endif
@if(count($ai_chat_search)>0)
    <ul class="m-0 p-0 list-none font-medium">
        @foreach($ai_chat_search as $item)
            <li class="p-2 px-3 border-solid border-b border-t-0 border-r-0 border-l-0 border-[--tblr-border-color] last:border-b-0 transition-colors hover:bg-slate-50  dark:hover:!bg-[rgba(255,255,255,0.05)]">
                <a href="{{LaravelLocalization::localizeUrl(route('dashboard.user.chat.chat', $item->slug))}}" class="d-flex align-items-center text-heading !no-underline">
                    <div class="avatar w-[43px] h-[43px] [&_svg]:w-[20px] [&_svg]:h-[20px] relative !me-2" style="background: {{$item->color}}">
                        @if( $item->slug == 'ai-chat-bot' )
                            <svg class="svg" width="57" height="54" viewBox="0 0 57 54" fill="none"
                                 xmlns="http://www.w3.org/2000/svg">
                                <path
                                    d="M0.387695 53.827V5.44295C0.387695 4.00269 0.870131 2.80012 1.835 1.83525C2.79987 0.870375 4.00244 0.387939 5.44271 0.387939H51.6603C53.1006 0.387939 54.3032 0.870375 55.268 1.83525C56.2329 2.80012 56.7153 4.00269 56.7153 5.44295V39.1433C56.7153 40.5836 56.2329 41.7861 55.268 42.751C54.3032 43.7159 53.1006 44.1983 51.6603 44.1983H10.0164L0.387695 53.827ZM3.51701 46.2505L8.69845 41.069H51.6603C52.222 41.069 52.6833 40.8885 53.0444 40.5274C53.4055 40.1663 53.586 39.705 53.586 39.1433V5.44295C53.586 4.88129 53.4055 4.41993 53.0444 4.05886C52.6833 3.69779 52.222 3.51725 51.6603 3.51725H5.44271C4.88105 3.51725 4.41969 3.69779 4.05861 4.05886C3.69754 4.41993 3.51701 4.88129 3.51701 5.44295V46.2505ZM3.51701 5.44295V3.51725V46.2505V5.44295ZM27.1674 36.375H29.9356V8.21122H27.1674V36.375ZM18.5618 30.1164H21.33V14.4698H18.5618V30.1164ZM10.7385 23.8578H13.5067V20.7285H10.7385V23.8578ZM35.773 30.1164H38.5412V14.4698H35.773V30.1164ZM43.5963 23.8578H46.3645V20.7285H43.5963V23.8578Z"
                                    fill="#0C6152"/>
                            </svg>
                        @else
                            {{$item->short_name}}
                        @endif
                    </div>
                    {{$item->name}}
                    <small class="ml-auto text-muted opacity-75">{{__('AI Chat Template')}}</small>
                </a>
            </li>
        @endforeach
    </ul>
@endif
@if(count($workbook_search)>0)
    <hr class="border-[2px]">
    <h3 class="m-0 py-[0.75rem] px-3 border-solid border-b border-t-0 border-r-0 border-l-0 border-[--tblr-border-color] text-[1rem] font-medium">{{__('Workbooks')}}</h3>
    <ul class="m-0 p-0 list-none">
        @foreach($workbook_search as $item)
        <li class="p-2 px-3 border-solid border-b border-t-0 border-r-0 border-l-0 border-[--tblr-border-color] last:border-b-0 transition-colors hover:bg-slate-50  dark:hover:!bg-[rgba(255,255,255,0.05)]">
			<a href="{{LaravelLocalization::localizeUrl(route('dashboard.user.openai.documents.single', $item->slug))}}" class="d-flex align-items-center text-heading !no-underline">
				<span class="avatar w-[43px] h-[43px] [&_svg]:w-[20px] [&_svg]:h-[20px] relative !me-2" style="background: {{$item->color}}">
					@if ( $item->image !== 'none' )
					{!! html_entity_decode($item->image) !!}
					@endif
				</span>
				{{$item->title}}
				<small class="ml-auto text-muted opacity-75">{{__('Workbook')}}</small>
			</a>
		</li>
        @endforeach
    </ul>
@endif

@if(isset($result) and $result=='null')
	<div class="p-6 font-medium text-center text-heading">
		<h3 class="mb-2">{{__('No results.')}}</h3>
		<p class="opacity-70">{{__('Please try with another word.')}}</p>
	</div>
@endif